// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using smart_learner.infrastructure;

#nullable disable

namespace smart_learner.infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smart_learner.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Mark William"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Json Smith"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "John Cena"
                        });
                });

            modelBuilder.Entity("Smart_learner.Domain.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("studentProfiles");
                });

            modelBuilder.Entity("Smart_learner.Domain.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe",
                            Level = 0,
                            Price = 50f
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Jane Smith",
                            Level = 1,
                            Price = 100f
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Alice Johnson",
                            Level = 0,
                            Price = 75f
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Bob Brown",
                            Level = 1,
                            Price = 120f
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Charlie Davis",
                            Level = 0,
                            Price = 60f
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Emily Wilson",
                            Level = 1,
                            Price = 110f
                        },
                        new
                        {
                            Id = 7,
                            FullName = "David Lee",
                            Level = 0,
                            Price = 80f
                        });
                });

            modelBuilder.Entity("Smart_learner.Domain.StudentProfile", b =>
                {
                    b.OwnsOne("Smart_learner.Domain.StudentFavourite", "StudentFavourite", b1 =>
                        {
                            b1.Property<int>("StudentProfileId")
                                .HasColumnType("integer");

                            b1.Property<int>("StudentId")
                                .HasColumnType("integer");

                            b1.Property<int>("TeacherId")
                                .HasColumnType("integer");

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("studentProfiles");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.Navigation("StudentFavourite")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
